interface BaseExercise{
  id: Int!
  fitnessId: Int!
  deps: Int!
}

type Exercise implements BaseExercise {
  id: Int!
  fitnessId: Int!
  deps: Int!
}

type ExerciseWithFitness implements BaseExercise {
  id: Int!
  fitnessId: Int!
  deps: Int!
  fitness: Fitness
}

type ExerciseHistorySet {
  weight: Float!
  repeat: Int!
}

type ExerciseHistoryData {
  id: Int!
  year: Int!
  month: Int!
  date: Int!
  fitnessId: Int!
  weightUnit: String!
  historyList: [ExerciseHistorySet!]!
}

type Query {
  getExerciseListByIds(ids: [Int!]): [ExerciseWithFitness!]
  getExerciseById(id: Int!): ExerciseWithFitness
  getExerciseListByScheduleId(
    scheduleId: Int
    offset: Int
    size: Int
  ): [ExerciseWithFitness!]
  getExerciseListByExercisePresetId(
    exercisePresetId: Int
    offset: Int
    size: Int
  ): [ExerciseWithFitness!]
  getExerciseFinishHistory(fitnessId: Int): [ExerciseHistoryData!]
}

input CreateExerciseByScheduleInput {
  scheduleId: Int!
  fitnessIds: [Int!]
}
input CreateExerciseByExercisePresetInput {
  exercisePresetId: Int!
  fitnessIds: [Int!]
}

input UpdateExerciseInput {
  id: Int!
  fitnessId: Int!
}

type Mutation {
  createExerciseBySchedule(exercise: CreateExerciseByScheduleInput): [ExerciseWithFitness!]
  
  createExerciseByExercisePreset(
    exercise: CreateExerciseByExercisePresetInput
  ): [ExerciseWithFitness!]

  updateExercise(exercise: UpdateExerciseInput): Exercise

  deleteExerciseById(id: Int): String
  deleteExerciseByIds(ids: [Int!]): String
}
